//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHotelService")]
    public interface IHotelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetHotelData", ReplyAction="http://tempuri.org/IHotelService/GetHotelDataResponse")]
        HotelsServiceLibrary.HotelDetails[] GetHotelData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetHotelData", ReplyAction="http://tempuri.org/IHotelService/GetHotelDataResponse")]
        System.Threading.Tasks.Task<HotelsServiceLibrary.HotelDetails[]> GetHotelDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetHotelById", ReplyAction="http://tempuri.org/IHotelService/GetHotelByIdResponse")]
        string GetHotelById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetHotelById", ReplyAction="http://tempuri.org/IHotelService/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<string> GetHotelByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelServiceChannel : Hotel.ServiceReference1.IHotelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServiceClient : System.ServiceModel.ClientBase<Hotel.ServiceReference1.IHotelService>, Hotel.ServiceReference1.IHotelService {
        
        public HotelServiceClient() {
        }
        
        public HotelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelsServiceLibrary.HotelDetails[] GetHotelData() {
            return base.Channel.GetHotelData();
        }
        
        public System.Threading.Tasks.Task<HotelsServiceLibrary.HotelDetails[]> GetHotelDataAsync() {
            return base.Channel.GetHotelDataAsync();
        }
        
        public string GetHotelById(int id) {
            return base.Channel.GetHotelById(id);
        }
        
        public System.Threading.Tasks.Task<string> GetHotelByIdAsync(int id) {
            return base.Channel.GetHotelByIdAsync(id);
        }
    }
}
